Backend feature/edit delete product
bounswe/bounswe2020group1 pull request #230
Opened 2020-12-07 17:03 UTC by onurkilic2301

# Description

Implementation of edit and delete product endpoints.

## Type of change

Please delete options that are not relevant.
- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# How Has This Been Tested?

Unit tests are implemented to test the new endpoints and the code passes all the existing and new tests.

**Test Configuration**:
* OS: MacOS
* Python: 3.8.5

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2020-12-08 16:12 UTC, onurkilic2301 commented
Added endpoints to add photos to specific products and deleting photos of the product.

2020-12-09 08:09 UTC, muratekici commented on backend/product/views.py
> +        product.delete()
I think this endpoint doesn't delete the image files. It updates the table though.

2020-12-09 08:10 UTC, muratekici requested changes
Can you delete the files also in the delete product endpont.

2020-12-09 08:15 UTC, onurkilic2301 commented
Requested changes are done!

2020-12-09 08:16 UTC, muratekici approved these changes
Looks great! We can merge it.

2020-12-09 08:17 UTC, merged